apiVersion: v1
kind: Service
metadata:
  name: responsible-ai-toxicity
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-toxicity
spec:
  type: ClusterIP
  ports:
  - port: 8001
  selector:
    app: responsible-ai-toxicity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: responsible-ai-toxicity
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-toxicity
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-toxicity
      version: v1
  template:
    metadata:
      labels:
        app: responsible-ai-toxicity
        version: v1
    spec:
      automountServiceAccountToken: false # Disable token mounting
      imagePullSecrets:
         - name: docker-secret
      containers:
      - envFrom:
        - configMapRef:
            name: safety-config
        image: <Image Name>
        imagePullPolicy: Always
        name: responsible-ai-toxicity
        ports:
        - containerPort: 8001
        securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL  # Drop all capabilities
            seccompProfile:
              type: RuntimeDefault
        resources:
            limits:
                cpu: '2'
                memory: '5Gi'