openapi_url: /api/v1/rai/admin/openapi.json
docs_url: /api/v1/rai/admin/docs
title: Infosys Responsible AI - responsible-ai-admin - OpenAPI 3.0
description: API specs for Infosys Responsible AI rai_admin pillar in OpenAPI 3.0 format
terms_of_service: https://www.infosys.com
contact:
    email: aina@infosys.com
license_info:
    name: Infosys
    url: https://www.infosys.com
version: v$version
openapi_tags:
    - name: rai_admin
      description: creating recognizer and account mapping
      externalDocs:
        description: Find out more
        url: https://www.infosys.com
