-
    name: infosys_responsible_ai_fairness
    version: 1.0.3
    build: 0.0.1
    description: Responsible AI
    long_description: infosys_responsible_ai_fairness
    classifiers: ["Programming Language :: Python :: 3",
                  "License :: OSI Approved :: MIT License",
                  "Operating System :: OS Independent",]
    package_dir: {"": "infosys_responsible_ai_fairness"}
    packages: infosys_responsible_ai_fairness
    python_requires: ['>=3.6']