apiVersion: v1
kind: ServiceAccount
metadata:
  name: responsible-ai-reporting-tool-sa
  namespace: irai-toolkit-test
automountServiceAccountToken: false
apiVersion: v1
kind: Service
metadata:
  name: responsible-ai-admin
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-admin
spec:
  type: ClusterIP
  ports:
  - port: 30016
  selector:
    app: responsible-ai-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: responsible-ai-admin
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-admin
      version: v1
  template:
    metadata:
      labels:
        app: responsible-ai-admin
        version: v1
    spec:
      automountServiceAccountToken: false # Disable token mounting
      imagePullSecrets:
         - name: docker-secret
      containers:
      - envFrom:
        - configMapRef:
            name: admin-config
        image: <Image Name>
        imagePullPolicy: Always
        name: responsible-ai-admin
        ports:
        - containerPort: 30016
        securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL  # Drop all capabilities
            seccompProfile:
              type: RuntimeDefault
        resources:
            limits:
                cpu: '1'
                memory: '3Gi'
