-
    name: privacy
    version: 1.0.3
    build: 0.0.1
    author: Amit Hegde
    author_email: amitumamaheshwar.h@infosys.com
    description: Infosys PII Analyzation & Anonymization System
    long_description: Infosys PII Analyzation & Anonymization System
    classifiers: ["Programming Language :: Python :: 3",
                  "License :: OSI Approved :: MIT License",
                  "Operating System :: OS Independent",]
    package_dir: {"": "privacy"}
    packages: privacy
    python_requires: ['>=3.6']
    include_package_data: True
    package_data:
        '': ['*.ini','*.pt','*.dcm','*.xml','*.env']