openapi_url: /v1/rai/backend/openapi.json
docs_url: /v1/rai/backend/docs
title: Infosys Responsible AI - responsible-ai-backend - OpenAPI 3.0
description: API specs for Infosys Responsible AI rai_backend pillar in OpenAPI 3.0 format
terms_of_service: https://www.infosys.com
contact:
    email: aina@infosys.com
license_info:
    name: Infosys
    url: https://www.infosys.com
version: v$version
openapi_tags:
    - name: rai_backend
      description: creating users and login management
      externalDocs:
        description: Find out more
        url: https://www.infosys.com