apiVersion: v1
kind: Service
metadata:
  name: responsible-ai-security-workbench
  namespace: irai-toolkit-test
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: responsible-ai-security-workbench
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: responsible-ai-security-workbench
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: responsible-ai-security-workbench
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-security-workbench
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-security-workbench
      version: v1
  template:
    metadata:
      labels:
        app: responsible-ai-security-workbench
        version: v1
    spec:
      automountServiceAccountToken: false # Disable token mounting
      imagePullSecrets:
         - name: docker-secret
      containers:
      - name: responsible-ai-security-workbench
        envFrom:
        - configMapRef:
            name: security-workbench-cosmos-config
        image: <Image Name>
        imagePullPolicy: Always
        name: responsible-ai-security-workbench
        ports:
        - containerPort: 80
        securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL  # Drop all capabilities
        resources:
          limits:
            cpu: '5'
            memory: '6Gi'
