apiVersion: v1
kind: Service
metadata:
  name: responsible-ai-questionnaire
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-questionnaire
spec:
  type: ClusterIP
  ports:
  - port: 30080
  selector:
    app: responsible-ai-questionnaire
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: responsible-ai-questionnaire
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-questionnaire
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-questionnaire
      version: v1
  template:
    metadata:
      labels:
        app: responsible-ai-questionnaire
        version: v1
    spec:
      automountServiceAccountToken: false # Disable token mounting
      imagePullSecrets:
         - name: docker-secret
      containers:
        - envFrom:
          - configMapRef:
              name: questionnaire-test-config
          image: <Image Name>
          imagePullPolicy: Always
          name: responsible-ai-questionnaire
          ports:
            - containerPort: 30080
          securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL  # Drop all capabilities
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
                cpu: '1'
                memory: '1Gi'
