apiVersion: v1
kind: Service
metadata:
  name: responsible-ai-rag-test
  namespace: irai-toolkit-test
    #  annotations:
    #    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: responsible-ai-rag-test
spec:
  type: ClusterIP
  ports:
  - port: 8002
  selector:
    app: responsible-ai-rag-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: responsible-ai-rag-test
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-rag-test
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-rag-test
      version: v1
  template:
    metadata:
      labels:
        app: responsible-ai-rag-test
        version: v1
    spec:
      automountServiceAccountToken: false # Disable token mounting
      imagePullSecrets:
         - name: docker-secret
      containers:
      - envFrom:
        - configMapRef:
            name: rag-test-config
        image: <Image Name>
        imagePullPolicy: Always
        name: responsible-ai-rag-test
        ports:
        - containerPort: 8002
        securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL  # Drop all capabilities
        resources:
            limits:
                cpu: '2'
                memory: '10Gi'
