apiVersion: v1
kind: Service
metadata:
  name: responsible-ai-upload-test
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-upload-test
spec:
  type: ClusterIP
  ports:
  - port: 30030
  selector:
    app: responsible-ai-upload-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: responsible-ai-upload-test
  namespace: irai-toolkit-test
  labels:
    app: responsible-ai-upload-test
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-upload-test
      version: v1
  template:
    metadata:
      labels:
        app: responsible-ai-upload-test
        version: v1
    spec:
      automountServiceAccountToken: false # Disable token mounting
      imagePullSecrets:
         - name: docker-secret
      containers:
      - name: responsible-ai-upload-test
        envFrom:
        - configMapRef:
            name: upload-test-config
        image: <Image Name>
        imagePullPolicy: Always
        name: responsible-ai-upload-test
        ports:
        - containerPort: 30030
        securityContext:
            runAsUser: 1000  # Non-root user
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL  # Drop all capabilities
            seccompProfile:
              type: RuntimeDefault
        resources:
          limits:
            cpu: '2'
            memory: '3Gi'
