-
    name: presidio_analyzer
    version: 4.1.0
    build: 0.0.1
    author: Amit Hegde
    author_email: amitumamaheshwar.h@infosys.com
    description: Infosys Intelligent Assistant
    long_description: Infosys Intelligent Assistant
    classifiers: ["Programming Language :: Python :: 3",
                  "License :: OSI Approved :: MIT License",
                  "Operating System :: OS Independent",]
    package_dir: {"": "presidio_analyzer"}
    packages: presidio_analyzer
    python_requires: ['>=3.6']